include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_return: error
    dead_code: warning

linter:
  rules:
    avoid_print: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    unnecessary_this: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    always_declare_return_types: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true
